### Open PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:opened",
  "date": "2024-03-29T02:41:56+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 0,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711654916973,
    "updatedDate": 1711654916973,
    "fromRef": {
      "id": "refs\/heads\/1branch",
      "displayId": "1branch",
      "latestCommit": "1fa061660486042ab31eb6a2c2bd69b5e47731f5",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "toRef": {
      "id": "refs\/heads\/master",
      "displayId": "master",
      "latestCommit": "19b53aeeb00a73fa376f4cbe140b830dda701ac5",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "locked": false,
    "author": {
      "user": {
        "name": "ivan.ivanov",
        "emailAddress": "ivan.ivanov@some-company.com",
        "active": true,
        "displayName": "Ivan Ivanov",
        "id": 2499,
        "slug": "ivan.ivanov",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
            }
          ]
        }
      },
      "role": "AUTHOR",
      "approved": false,
      "status": "UNAPPROVED"
    },
    "reviewers": [],
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/2"
        }
      ]
    }
  }
}

### Decline PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:declined",
  "date": "2024-03-29T02:41:48+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "DECLINED",
    "open": false,
    "closed": true,
    "createdDate": 1711654833803,
    "updatedDate": 1711654908182,
    "closedDate": 1711654908182,
    "fromRef": {
      "id": "refs\/heads\/1branch",
      "displayId": "1branch",
      "latestCommit": "1fa061660486042ab31eb6a2c2bd69b5e47731f5",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "toRef": {
      "id": "refs\/heads\/master",
      "displayId": "master",
      "latestCommit": "19b53aeeb00a73fa376f4cbe140b830dda701ac5",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "locked": false,
    "author": {
      "user": {
        "name": "ivan.ivanov",
        "emailAddress": "ivan.ivanov@some-company.com",
        "active": true,
        "displayName": "Ivan Ivanov",
        "id": 2499,
        "slug": "ivan.ivanov",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
            }
          ]
        }
      },
      "role": "AUTHOR",
      "approved": false,
      "status": "UNAPPROVED"
    },
    "reviewers": [],
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/1"
        }
      ]
    }
  }
}

### Added comment to PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:comment:added",
  "date": "2024-04-08T00:59:04+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https://git.some-company.tech/users/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711657855549,
    "updatedDate": 1711722969521,
    "locked": false,
    "author": {
      "user": {
        "name": "ivan.ivanov",
        "emailAddress": "ivan.ivanov@some-company.com",
        "active": true,
        "displayName": "Ivan Ivanov",
        "id": 2499,
        "slug": "ivan.ivanov",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https://git.some-company.tech/users/ivan.ivanov"
            }
          ]
        }
      },
      "role": "AUTHOR",
      "approved": false,
      "status": "UNAPPROVED"
    },
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https://git.some-company.tech/projects/SBX/repos/iivanov-test/pull-requests/3"
        }
      ]
    }
  },
  "comment": {
    "properties": {
      "repositoryId": 2912
    },
    "id": 425631,
    "version": 0,
    "text": "Test",
    "author": {
      "name": "ivan.ivanov",
      "emailAddress": "ivan.ivanov@some-company.com",
      "active": true,
      "displayName": "Ivan Ivanov",
      "id": 2499,
      "slug": "ivan.ivanov",
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https://git.some-company.tech/users/ivan.ivanov"
          }
        ]
      }
    },
    "createdDate": 1712512744728,
    "updatedDate": 1712512744728,
    "comments": [],
    "threadResolved": false,
    "severity": "BLOCKER",
    "state": "OPEN"
  }
}

### Edited comment in PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:comment:edited",
  "date": "2024-04-08T05:39:43+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711657855549,
    "updatedDate": 1711722969521,
    "locked": false,
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/3"
        }
      ]
    }
  },
  "comment": {
    "properties": {
      "repositoryId": 2912
    },
    "id": 425631,
    "version": 1,
    "text": "test1",
    "author": {
      "name": "ivan.ivanov",
      "emailAddress": "ivan.ivanov@some-company.com",
      "active": true,
      "displayName": "Ivan Ivanov",
      "id": 2499,
      "slug": "ivan.ivanov",
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
          }
        ]
      }
    },
    "createdDate": 1712529570047,
    "updatedDate": 1712529583442,
    "comments": [],
    "threadResolved": false,
    "severity": "NORMAL",
    "state": "OPEN"
  },
  "previousComment": "test"
}

### Comment thread resolved in PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:comment:edited",
  "date": "2024-04-08T05:39:43+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711657855549,
    "updatedDate": 1711722969521,
    "locked": false,
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/3"
        }
      ]
    }
  },
  "comment": {
    "properties": {
      "repositoryId": 2912
    },
    "id": 425631,
    "version": 1,
    "text": "test1",
    "author": {
      "name": "ivan.ivanov",
      "emailAddress": "ivan.ivanov@some-company.com",
      "active": true,
      "displayName": "Ivan Ivanov",
      "id": 2499,
      "slug": "ivan.ivanov",
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
          }
        ]
      }
    },
    "createdDate": 1712529570047,
    "updatedDate": 1712529583442,
    "comments": [],
    "threadResolved": true,
    "threadResolver": {
      "displayName": "Ivan Ivanov"
    },
    "severity": "NORMAL",
    "state": "OPEN"
  },
  "previousComment": "test"
}

### Deleted comment in PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:comment:deleted",
  "date": "2024-04-08T17:08:11+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711657855549,
    "updatedDate": 1711722969521,
    "locked": false,
    "author": {
      "user": {
        "name": "ivan.ivanov",
        "emailAddress": "ivan.ivanov@some-company.com",
        "active": true,
        "displayName": "Ivan Ivanov",
        "id": 2499,
        "slug": "ivan.ivanov",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
            }
          ]
        }
      },
      "role": "AUTHOR",
      "approved": false,
      "status": "UNAPPROVED"
    },
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/3"
        }
      ]
    }
  },
  "comment": {
    "id": 425632,
    "version": 1,
    "text": "test1",
    "author": {
      "name": "ivan.ivanov",
      "emailAddress": "ivan.ivanov@some-company.com",
      "active": true,
      "displayName": "Ivan Ivanov",
      "id": 2499,
      "slug": "ivan.ivanov",
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
          }
        ]
      }
    },
    "createdDate": 1712529570047,
    "updatedDate": 1712529583442,
    "comments": [],
    "threadResolved": false,
    "severity": "NORMAL",
    "state": "OPEN"
  }
}

### Deleted PR
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:deleted",
  "date": "2024-04-08T17:09:36+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "2branch",
    "description": "* 1branch commit\n* 1branch commit\n* 2branch commit",
    "state": "DECLINED",
    "open": false,
    "closed": true,
    "createdDate": 1712516619256,
    "updatedDate": 1712516630720,
    "closedDate": 1712516630720,
    "locked": false,
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/4"
        }
      ]
    }
  }
}

### PR from ref updated
POST {{host}}/webhook/bitbucket
Content-Type: application/json

{
  "eventKey": "pr:from_ref_updated",
  "date": "2024-04-08T17:18:36+0700",
  "actor": {
    "name": "ivan.ivanov",
    "emailAddress": "ivan.ivanov@some-company.com",
    "active": true,
    "displayName": "Ivan Ivanov",
    "id": 2499,
    "slug": "ivan.ivanov",
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
        }
      ]
    }
  },
  "pullRequest": {
    "id": 1,
    "version": 1,
    "title": "1branch commit",
    "state": "OPEN",
    "open": true,
    "closed": false,
    "createdDate": 1711657855549,
    "updatedDate": 1712571516502,
    "fromRef": {
      "id": "refs\/heads\/1branch",
      "displayId": "1branch",
      "latestCommit": "d4400720e83f5f330987c621041b0bb748849c30",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "toRef": {
      "id": "refs\/heads\/master",
      "displayId": "master",
      "latestCommit": "19b53aeeb00a73fa376f4cbe140b830dda701ac5",
      "type": "BRANCH",
      "repository": {
        "slug": "iivanov-test",
        "id": 2912,
        "name": "iivanov-test",
        "hierarchyId": "dfd9d9a89e389722a9d5",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
          "key": "SBX",
          "id": 355,
          "name": "Sandbox",
          "public": true,
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/projects\/SBX"
              }
            ]
          }
        },
        "public": false,
        "archived": false,
        "links": {
          "clone": [
            {
              "href": "https:\/\/git.some-company.tech\/scm\/sbx\/iivanov-test.git",
              "name": "http"
            },
            {
              "href": "ssh:\/\/git@git.some-company.tech:7999\/sbx\/iivanov-test.git",
              "name": "ssh"
            }
          ],
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/browse"
            }
          ]
        }
      }
    },
    "locked": false,
    "author": {
      "user": {
        "name": "ivan.ivanov",
        "emailAddress": "ivan.ivanov@some-company.com",
        "active": true,
        "displayName": "Ivan Ivanov",
        "id": 2499,
        "slug": "ivan.ivanov",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https:\/\/git.some-company.tech\/users\/ivan.ivanov"
            }
          ]
        }
      },
      "role": "AUTHOR",
      "approved": false,
      "status": "UNAPPROVED"
    },
    "reviewers": [
      {
        "user": {
          "name": "bot-automerge",
          "emailAddress": "devnull2@some-company.ru",
          "active": true,
          "displayName": "Bot Automerge",
          "id": 2353,
          "slug": "bot-automerge",
          "type": "NORMAL",
          "links": {
            "self": [
              {
                "href": "https:\/\/git.some-company.tech\/users\/bot-automerge"
              }
            ]
          }
        },
        "role": "REVIEWER",
        "approved": false,
        "status": "UNAPPROVED"
      }
    ],
    "participants": [],
    "links": {
      "self": [
        {
          "href": "https:\/\/git.some-company.tech\/projects\/SBX\/repos\/iivanov-test\/pull-requests\/3"
        }
      ]
    }
  },
  "previousFromHash": "5701e07338ddebc42c8acd549e45996f28932401"
}